### ISSUE TITLE
TODO list V0.1

### ISSUE THREAD

**Issue by AFCMS** [minetest-palamod/palamod#1]
- [x] Minerals
   - [x] Amethist
   - [x] Titanium
   - [x] Paladium
   - [x] Green Paladium
   - [x] Findium
- [ ] Weapons
   - [x] Swords
   - [ ] Bow
   - [x] Infernal Knocker
- [ ] Tools ~~(need change in mcl: https://git.minetest.land/Wuzzy/MineClone2/issues/868)~~
   - [x] Pick
   - [x] Axe
   - [x] Showel 
   - [ ] Hammer
- [x] Armor
   - [x] Amethist
   - [x] Titanium
   - [x] Paladium
   - [x] Green Paladium
   - [x] Endium
   - [ ] Travel
   - [x] Invisible
- [ ] Luckyblocks (#3)
- [ ] Craftitems
   - [x] Sticks
   - [ ] Orbs
   - [ ] Compressed 
- [ ] TNT
   - [ ] Wither
   - [ ] Endium
   - [ ] Big
   - [ ] Effect
   - [ ] Sponge
- [ ] Obsidians
   - [x] Door
   - [x] Trapdoor
   - [x] Hardened
   - [ ] Compact
   - [x] Lava
   - [x] Sulfur
   - [x] Boom
   - [ ] Slime
   - [x] Poison
   - [ ] Wither
   - [x] Spike
- [ ] Dynamites
   - [ ] Better entity 
   - [x] Base
   - [x] Big
   - [x] Endium
   - [x] Ninja?
- [ ] Looting
   - [x] Online Detector
   - [x] Caveblock
   - [x] Chest Explorer
   - [ ] Unclaim Finder (base => will be client side with sscsm)
      - [ ] Green
      - [ ] Orange
      - [ ] Red
- [ ] Basic Plants 
   - [ ] XP bush
   - [ ] Fertilised dirt
   - [ ] Harpagophytum
   - [ ] Hunter Plant
- [ ] External Projects
   - [ ] Economy System (https://github.com/minetest-palamod/mc_economy)
   - [ ] Faction Mod (https://github.com/minetest-palamod/mc_faction)
- [ ] Textures for alt_tp (https://github.com/minetest/minetest/issues/10829)
- [x] .luacheckrc
