### ISSUE TITLE
TODO Luckyblock

### ISSUE THREAD

**Issue by AFCMS** [minetest-palamod/palamod#3]
- [ ] Clean code
   - [x] pairs() => ipairs()
   - [x] length operator
   - [ ] global => local
- [ ] Loot functions (must open pr/feature request to mt for some)
- [ ] Loot textures
- [ ] Translation (Fr)
- [ ] Clean transition in GUI
- [ ] Client GUI? (sscsm)
