### ISSUE TITLE
Engine features needed

### ISSUE THREAD

**Issue by AFCMS** [minetest-palamod/palamod#9]
:+1: then up!

- [ ] SSCSM https://github.com/minetest/minetest/issues/10594
- [ ] Texture pack extension https://github.com/minetest/minetest/issues/10829
- [ ] Server send settings https://github.com/minetest/minetest/issues/11227
- [ ] CSM/SSCSM access to local settings https://github.com/minetest/minetest/issues/10382
- [ ] Formspec replacement https://github.com/minetest/minetest/issues/6527
- [ ] HUD https://github.com/minetest/minetest/issues/10548
